name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          # just perform install
          runTests: false

      - name: Lint files
        run: npm run lint

      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm start -- --host
          wait-on: 'http://localhost:5173'
